-- Inserción de registros en la tabla 'refugio'

USE plataforma_adopcion_mascotas;

INSERT INTO `refugio` (`id_refugio`,`nombre`,`direccion`,`telefono`,`email`,`website`) VALUES (1,'Refugio Feliz','Calle Alegría 123, Ciudad',5551234,'contacto@refugiofeliz.org','www.refugiofeliz.org');
INSERT INTO `refugio` (`id_refugio`,`nombre`,`direccion`,`telefono`,`email`,`website`) VALUES (2,'Hogar Animal','Avenida Central 456, Ciudad',5555678,'info@hogaranimal.com','www.hogaranimal.com');
INSERT INTO `refugio` (`id_refugio`,`nombre`,`direccion`,`telefono`,`email`,`website`) VALUES (3,'Refugio Esperanza Animal','12718 Osborne Square',1864915326,'jeremylawrence@hotmail.com','www.esperanzaanimal.com.mx');
INSERT INTO `refugio` (`id_refugio`,`nombre`,`direccion`,`telefono`,`email`,`website`) VALUES (4,'Santuario Vida Nueva','532 Johnson Viaduct Suite 653',8195630155,'lrusso@gmail.com','www.vidanuevasantuario.org');
INSERT INTO `refugio` (`id_refugio`,`nombre`,`direccion`,`telefono`,`email`,`website`) VALUES (5,'Proteccion Animal Amparo','505 Jose Manors',2859633540,'elizabethdean@thompson-wright.biz','www.amparoanimal.org');
INSERT INTO `refugio` (`id_refugio`,`nombre`,`direccion`,`telefono`,`email`,`website`) VALUES (6,'Manos Amigas para Animales','8683 Roberts Ridge',9304273854,'amyraymond@gmail.com','www.manosamigasanimales.com');
INSERT INTO `refugio` (`id_refugio`,`nombre`,`direccion`,`telefono`,`email`,`website`) VALUES (7,'Corazon Animal Refugio','487 Nathan Canyon',1777040172,'davenporttara@jones.com','www.corazonanimal.org');
INSERT INTO `refugio` (`id_refugio`,`nombre`,`direccion`,`telefono`,`email`,`website`) VALUES (8,'Albergue Amigos de Cuatro Patas','45463 Sellers Cape',8305324252,'kaylathompson@johnson.net','www.amigoscuatropatas.mx');
INSERT INTO `refugio` (`id_refugio`,`nombre`,`direccion`,`telefono`,`email`,`website`) VALUES (9,'Rescate y Refugio Canino','361 Brandon Harbor',6598863689,'angiedaniel@hotmail.com','www.rescatecanino.org');
INSERT INTO `refugio` (`id_refugio`,`nombre`,`direccion`,`telefono`,`email`,`website`) VALUES (10,'Refugio Gato y Perro','6785 Jason Highway Apt. 913',8708983751,'wmoore@yahoo.com','www.gatoyperrorefugio.org');
INSERT INTO `refugio` (`id_refugio`,`nombre`,`direccion`,`telefono`,`email`,`website`) VALUES (11,'Hogar Temporal para Mascotas','1944 Christopher Trafficway',9681467536,'christine74@richardson-choi.net','www.hogartemporalmascotas.com');
INSERT INTO `refugio` (`id_refugio`,`nombre`,`direccion`,`telefono`,`email`,`website`) VALUES (12,'Hogar de Mascotas Felices','58035 Burke Tunnel Apt. 111',9971079273,'fsimmons@gmail.com','www.hogarfelicesmascotas.org');

-- Inserción de registros en la tabla 'usuario'

INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (1,'Noelia','Martínez','NoeliaMartinez@example.com','hashed_password_1',5558765,'Calle Luna 789, Ciudad','administrador','2024-11-21');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (2,'Carlos','Gómez','CarlosGomez@example.com','hashed_password_2',5552345,'Avenida Sol 345, Ciudad','administrador','2024-10-15');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (3,'María','López','MariaLopez@example.com','hashed_password_3',5556789,'Plaza Norte 101, Ciudad','adoptador','2024-09-10');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (4,'Isabela','Suarez','IsabelaSuareza@example.com','hashed_password_4',9669318885,'022 Mark Prairie Suite 776','adoptador','2004-03-12');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (5,'Mara','Guzman','MaraGuzmana@example.com','hashed_password_5',6272160957,'59908 Morris Circles Apt. 212','adoptador','2022-04-02');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (6,'Lucia','Diaz','LuciaDiaza@example.com','hashed_password_6',5680967855,'3831 Carter Creek Suite 370','adoptador','2007-04-19');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (7,'Martina','Ortiz','MartinaOrtiza@example.com','hashed_password_7',7608713908,'6465 Garcia Field Apt. 205','adoptador','2004-03-14');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (8,'Luis','Castro','LuisCastroa@example.com','hashed_password_8',2420846829,'80976 Smith Prairie Suite 279','adoptador','2010-12-20');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (9,'Carlos','Rojas','CarlosRojasa@example.com','hashed_password_9',4046292067,'70025 Martinez Causeway','adoptador','2009-12-27');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (10,'Diego','Perez','DiegoPereza@example.com','hashed_password_10',8439501459,'09993 Sutton Mountain','adoptador','2016-03-09');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (11,'Isabela','Rojas','IsabelaRojasa@example.com','hashed_password_11',4758063996,'181 Bradley Passage','adoptador','2004-12-04');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (12,'Diego','Hernandez','DiegoHernandeza@example.com','hashed_password_12',7460975522,'62068 Donald Road','adoptador','2002-07-08');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (13,'Luis','Romero','LuisRomeroa@example.com','hashed_password_13',4205571415,'8165 Garner Ville','adoptador','2008-07-01');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (14,'Juan','Martinez','JuanMartineza@example.com','hashed_password_14',1773391440,'0102 Winters Corner Suite 019','adoptador','2024-03-19');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (15,'Alejandro','Ortiz','AlejandroOrtiza@example.com','hashed_password_15',1624902635,'9697 Ramirez Plains','adoptador','2016-01-15');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (16,'Martina','Perez','MartinaPereza@example.com','hashed_password_16',8312982519,'87269 Diane Viaduct Suite 673','adoptador','2017-05-21');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (17,'Sofia','Romero','SofiaRomeroa@example.com','hashed_password_17',9643083136,'537 Miguel Falls','adoptador','2013-03-04');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (18,'Lucia','Flores','LuciaFloresa@example.com','hashed_password_18',2080818229,'8182 Brown Summit','adoptador','2008-08-16');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (19,'Lucia','Rodriguez','LuciaRodrigueza@example.com','hashed_password_19',3960457267,'845 Dixon Stravenue','adoptador','2004-05-14');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (20,'Martina','Rodriguez','MartinaRodrigueza@example.com','hashed_password_20',2786175205,'54803 Peter Ferry','adoptador','2005-06-04');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (21,'Mateo','Mendoza','MateoMendozaa@example.com','hashed_password_21',8227909658,'83758 Lewis Roads Suite 927','adoptador','2022-12-21');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (22,'Mateo','Guzman','MateoGuzmana@example.com','hashed_password_22',9885913209,'666 Cannon Village Suite 869','adoptador','2012-05-20');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (23,'Emiliano','Rodriguez','EmilianoRodrigueza@example.com','hashed_password_23',2705223873,'1082 Price Place','adoptador','2000-09-25');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (24,'Emiliano','Ramirez','EmilianoRamireza@example.com','hashed_password_24',6921211379,'031 Leah Forge','adoptador','2020-10-18');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (25,'Mateo','Rojas','MateoRojasa@example.com','hashed_password_25',8023343205,'07544 Nelson Drive Suite 724','adoptador','2021-04-09');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (26,'Nicolas','Guzman','NicolasGuzmana@example.com','hashed_password_26',2621709244,'8088 Clinton Meadows','adoptador','2016-02-09');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (27,'Juan','Morales','JuanMoralesa@example.com','hashed_password_27',2973084275,'4859 Joseph Manor','adoptador','2012-07-29');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (28,'Isabela','Ortiz','IsabelaOrtiza@example.com','hashed_password_28',3798836673,'05444 Jason Point Apt. 804','adoptador','2015-11-14');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (29,'Marta','Romero','MartaRomeroa@example.com','hashed_password_29',7423443760,'036 Smith Way Apt. 983','adoptador','2023-03-15');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (30,'Gabriel','Garcia','GabrielGarciaa@example.com','hashed_password_30',6937352221,'634 Shirley Tunnel','adoptador','2021-12-22');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (31,'Isabela','Perez','IsabelaPereza@example.com','hashed_password_31',2688739261,'965 Young Ridges Suite 086','adoptador','2000-08-14');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (32,'Camila','Rodriguez','CamilaRodrigueza@example.com','hashed_password_32',2354810332,'52032 Amy Park Apt. 128','adoptador','2015-01-20');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (33,'Gabriel','Vargas','GabrielVargasa@example.com','hashed_password_33',3484013693,'2598 Joshua Mill','adoptador','2017-09-24');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (34,'Mateo','Ortiz','MateoOrtiza@example.com','hashed_password_34',6682369020,'245 Frank Tunnel','adoptador','2022-05-08');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (35,'Josue','Martinez','JosueMartineza@example.com','hashed_password_35',1251837417,'38180 Lynch Passage Suite 235','adoptador','2016-11-13');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (36,'Diego','Romero','DiegoRomeroa@example.com','hashed_password_36',1676573785,'809 Chavez Turnpike','adoptador','2004-07-02');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (37,'Pedro','Diaz','PedroDiaza@example.com','hashed_password_37',7710485818,'4064 Guerrero Stravenue Suite 383','adoptador','2011-01-11');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (38,'Isabela','Ramirez','IsabelaRamireza@example.com','hashed_password_38',9358641000,'04460 Dean Points','adoptador','2021-04-09');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (39,'Luis','Gomez','LuisGomeza@example.com','hashed_password_39',4244718681,'77017 James Canyon Apt. 106','adoptador','2012-08-26');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (40,'Carlos','Gomez','CarlosGomeza@example.com','hashed_password_40',6127582759,'9382 Courtney Summit Suite 163','adoptador','2001-03-13');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (41,'Ana','Guzman','AnaGuzmana@example.com','hashed_password_41',9480151464,'12262 Murphy Ways','adoptador','2022-08-02');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (42,'Camila','Hernandez','CamilaHernandeza@example.com','hashed_password_42',7986657644,'5592 Wright Shoal Apt. 785','adoptador','2018-03-27');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (43,'Emiliano','Ortiz','EmilianoOrtiza@example.com','hashed_password_43',7846319647,'98018 Anthony Avenue','adoptador','2006-09-09');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (44,'Juan','Gomez','JuanGomeza@example.com','hashed_password_44',9397221084,'65442 Joshua Gateway Apt. 000','adoptador','2019-02-09');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (45,'Alejandro','Martinez','AlejandroMartineza@example.com','hashed_password_45',7760330726,'45856 Caleb Manors Apt. 747','adoptador','2003-04-30');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (46,'Valentina','Rodriguez','ValentinaRodrigueza@example.com','hashed_password_46',7080506786,'574 Lisa Track Apt. 890','adoptador','2011-11-15');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (47,'Gabriel','Lopez','GabrielLopeza@example.com','hashed_password_47',7549682268,'983 Crystal Stream Apt. 600','adoptador','2020-10-28');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (48,'Juan','Lopez','JuanLopeza@example.com','hashed_password_48',7868611172,'7695 Rivas Crest Apt. 863','adoptador','2012-05-21');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (49,'Camila','Suarez','CamilaSuareza@example.com','hashed_password_49',2116404435,'22096 Haley Stravenue','adoptador','2014-08-19');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (50,'Maria','Suarez','MariaSuareza@example.com','hashed_password_50',2671271489,'92236 Lin Ways Apt. 329','adoptador','2004-10-16');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (51,'Marcela','Rojas','MarcelaRojasa@example.com','hashed_password_51',2263228928,'997 David Summit','adoptador','2007-07-21');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (52,'Gonzalo','Suarez','GonzaloSuareza@example.com','hashed_password_52',9877379119,'978 Mary Street Apt. 263','adoptador','2009-06-17');
INSERT INTO `usuario` (`id_usuario`,`nombre`,`apellido`,`email`,`contraseña`,`telefono`,`direccion`,`tipo_usuario`,`fecha_registro`) VALUES (53,'Sebastian','Vargas','SebastianVargasa@example.com','hashed_password_53',6417590305,'329 Devin Ways','adoptador','2001-03-12');

-- Inserción de registros en la tabla 'mascota'

INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (1,'Max','Perro','2019-05-15','macho','grande',1,'Perro juguetón y cariñoso. Ideal para familias.',1);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (2,'Luna','Gato','2019-08-10','hembra','chico',1,'Gatita tímida pero muy dulce.',2);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (3,'Rex','Perro','2019-01-20','macho','mediano',1,'Perro rescatado en busca de un hogar tranquilo.',1);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (4,'Mia','Conejo','2023-02-14','hembra','chico',1,'Conejo activo y saludable, ideal para niños.',2);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (5,'Scott','Gato','2021-06-16','macho','chico',1,'Gato curioso que ama explorar cada rincon y descansar bajo el sol.',12);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (6,'Victor','Reptil','2019-03-20','hembra','mediano',1,'Reptil tranquilo que se siente feliz en un ambiente calido y seguro.',5);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (7,'Charles','Perro','2021-05-26','macho','mediano',1,'Perro muy amigable que disfruta de largos paseos y juegos con su familia.',1);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (8,'Robin','Ave','2023-07-02','macho','chico',1,'Ave alegre que llena el lugar con su canto y su energia vibrante.',2);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (9,'Robert','Reptil','2018-06-02','desconocido','grande',1,'Reptil tranquilo que se siente feliz en un ambiente calido y seguro.',7);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (10,'Brianna','Ave','2018-03-07','hembra','chico',1,'Ave alegre que llena el lugar con su canto y su energia vibrante.',6);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (11,'Carlos','Gato','2016-05-20','hembra','grande',1,'Gato curioso que ama explorar cada rincon y descansar bajo el sol.',11);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (12,'Kevin','Conejo','2018-10-15','macho','mediano',1,'Conejito especial que merece todo el cariÃ±o y cuidado del mundo.',10);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (13,'Steven','Conejo','2022-12-20','macho','mediano',1,'Conejito especial que merece todo el cariÃ±o y cuidado del mundo.',2);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (14,'Rodney','Reptil','2018-06-26','desconocido','chico',1,'Reptil tranquilo que se siente feliz en un ambiente calido y seguro.',2);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (15,'Deborah','Conejo','2018-06-19','macho','chico',1,'Conejito especial que merece todo el cariÃ±o y cuidado del mundo.',2);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (16,'Crystal','Gato','2021-03-12','hembra','chico',1,'Gato curioso que ama explorar cada rincon y descansar bajo el sol.',11);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (17,'Jane','Gato','2019-09-09','macho','grande',1,'Gato curioso que ama explorar cada rincon y descansar bajo el sol.',10);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (18,'Andrew','Conejo','2019-11-11','macho','chico',1,'Conejito especial que merece todo el cariÃ±o y cuidado del mundo.',5);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (19,'Gary','Ave','2021-02-08','hembra','chico',1,'Ave alegre que llena el lugar con su canto y su energia vibrante.',5);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (20,'Heather','Reptil','2023-01-07','macho','chico',1,'Reptil tranquilo que se siente feliz en un ambiente calido y seguro.',1);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (21,'Cody','Perro','2017-11-16','macho','chico',1,'Perro muy amigable que disfruta de largos paseos y juegos con su familia.',9);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (22,'Travis','Ave','2017-05-22','desconocido','chico',1,'Ave alegre que llena el lugar con su canto y su energia vibrante.',3);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (23,'Frank','Gato','2021-02-11','macho','mediano',1,'Gato curioso que ama explorar cada rincon y descansar bajo el sol.',3);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (24,'Calvin','Reptil','2019-02-21','hembra','mediano',1,'Reptil tranquilo que se siente feliz en un ambiente calido y seguro.',3);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (25,'Deborah','Reptil','2019-03-05','desconocido','chico',1,'Reptil tranquilo que se siente feliz en un ambiente calido y seguro.',4);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (26,'Michael','Ave','2022-07-14','desconocido','chico',1,'Ave alegre que llena el lugar con su canto y su energia vibrante.',6);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (27,'Eric','Gato','2015-02-12','macho','chico',1,'Gato curioso que ama explorar cada rincon y descansar bajo el sol.',1);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (28,'Jasmine','Reptil','2019-01-13','macho','chico',1,'Reptil tranquilo que se siente feliz en un ambiente calido y seguro.',5);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (29,'Nicholas','Ave','2022-02-16','macho','chico',1,'Ave alegre que llena el lugar con su canto y su energia vibrante.',8);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (30,'Keith','Reptil','2015-04-13','hembra','chico',1,'Reptil tranquilo que se siente feliz en un ambiente calido y seguro.',8);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (31,'Mitchell','Gato','2018-02-11','macho','mediano',1,'Gato curioso que ama explorar cada rincon y descansar bajo el sol.',8);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (32,'Susan','Perro','2019-03-02','hembra','grande',1,'Perro muy amigable que disfruta de largos paseos y juegos con su familia.',12);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (33,'Wendy','Gato','2021-11-22','hembra','chico',1,'Gato curioso que ama explorar cada rincon y descansar bajo el sol.',1);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (34,'Clayton','Ave','2020-04-18','desconocido','chico',1,'Ave alegre que llena el lugar con su canto y su energia vibrante.',1);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (35,'Jennifer','Reptil','2023-08-18','macho','grande',1,'Reptil tranquilo que se siente feliz en un ambiente calido y seguro.',1);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (36,'April','Ave','2019-02-12','macho','chico',1,'Ave alegre que llena el lugar con su canto y su energia vibrante.',12);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (37,'Rachel','Reptil','2018-01-06','desconocido','grande',1,'Reptil tranquilo que se siente feliz en un ambiente calido y seguro.',12);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (38,'Deanna','Ave','2016-11-16','desconocido','chico',1,'Ave alegre que llena el lugar con su canto y su energia vibrante.',7);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (39,'Karen','Conejo','2019-03-22','hembra','mediano',1,'Conejito especial que merece todo el cariÃ±o y cuidado del mundo.',7);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (40,'Jared','Gato','2023-10-28','desconocido','grande',1,'Gato curioso que ama explorar cada rincon y descansar bajo el sol.',9);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (41,'Jeffrey','Perro','2019-09-18','macho','grande',1,'Perro muy amigable que disfruta de largos paseos y juegos con su familia.',1);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (42,'Michelle','Perro','2016-12-28','hembra','chico',1,'Perro muy amigable que disfruta de largos paseos y juegos con su familia.',2);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (43,'Paul','Perro','2023-09-09','macho','grande',1,'Perro muy amigable que disfruta de largos paseos y juegos con su familia.',10);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (44,'Kristopher','Gato','2015-12-05','hembra','chico',1,'Gato curioso que ama explorar cada rincon y descansar bajo el sol.',11);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (45,'Timothy','Conejo','2018-06-12','hembra','mediano',1,'Conejito especial que merece todo el cariÃ±o y cuidado del mundo.',11);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (46,'Christopher','Reptil','2017-11-24','hembra','grande',1,'Reptil tranquilo que se siente feliz en un ambiente calido y seguro.',10);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (47,'Edwin','Perro','2018-10-02','macho','mediano',1,'Perro muy amigable que disfruta de largos paseos y juegos con su familia.',6);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (48,'Erin','Gato','2022-02-12','hembra','chico',1,'Gato curioso que ama explorar cada rincon y descansar bajo el sol.',6);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (49,'Mike','Conejo','2017-06-12','macho','grande',1,'Conejito especial que merece todo el cariÃ±o y cuidado del mundo.',6);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (50,'Jason','Ave','2022-08-07','macho','chico',1,'Ave alegre que llena el lugar con su canto y su energia vibrante.',4);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (51,'Cassidy','Reptil','2023-11-26','hembra','chico',1,'Reptil tranquilo que se siente feliz en un ambiente calido y seguro.',4);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (52,'Keith','Ave','2018-03-29','hembra','chico',1,'Ave alegre que llena el lugar con su canto y su energia vibrante.',2);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (53,'Matthew','Conejo','2022-04-08','hembra','chico',1,'Conejito especial que merece todo el cariÃ±o y cuidado del mundo.',1);
INSERT INTO `mascota` (`id_mascota`,`nombre`,`especie`,`fecha_nacimiento`,`sexo`,`tamaño`,`estirilizado`,`descripcion`,`id_refugio`) VALUES (54,'Jordan','Perro','2023-12-06','hembra','grande',1,'Perro muy amigable que disfruta de largos paseos y juegos con su familia.',1);

-- Inserción de registros en la tabla 'solicitud_adopcion'

INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (1,'2020-01-05','pendiente',30,1);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (2,'2020-01-20','rechazada',3,2);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (3,'2020-01-27','rechazada',30,3);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (4,'2023-02-23','aprobada',51,53);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (5,'2020-03-12','aprobada',22,6);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (6,'2022-03-24','rechazada',17,5);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (7,'2020-04-28','aprobada',34,17);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (8,'2023-05-04','rechazada',27,2);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (9,'2021-09-09','aprobada',23,19);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (10,'2020-09-13','pendiente',19,37);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (11,'2022-09-18','aprobada',21,33);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (12,'2022-10-07','aprobada',43,5);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (13,'2024-12-05','pendiente',38,35);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (14,'2020-12-21','rechazada',8,12);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (15,'2020-12-26','aprobada',31,32);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (16,'2020-12-30','rechazada',52,9);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (17,'2023-02-11','rechazada',11,26);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (18,'2021-02-18','pendiente',37,41);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (19,'2021-02-23','rechazada',13,39);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (20,'2021-02-28','aprobada',44,42);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (21,'2023-03-05','aprobada',49,13);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (22,'2021-03-26','rechazada',15,14);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (23,'2021-05-24','rechazada',25,10);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (24,'2021-08-01','rechazada',7,12);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (25,'2021-10-02','rechazada',12,10);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (26,'2021-12-14','rechazada',21,15);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (27,'2022-01-04','rechazada',37,45);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (28,'2022-01-04','pendiente',49,9);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (29,'2022-01-27','aprobada',16,30);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (30,'2022-02-20','pendiente',47,22);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (31,'2022-04-26','rechazada',6,47);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (32,'2022-06-16','pendiente',4,31);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (33,'2023-07-01','aprobada',16,48);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (34,'2022-07-22','pendiente',22,10);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (35,'2022-09-22','rechazada',53,11);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (36,'2022-10-22','rechazada',11,34);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (37,'2022-10-29','aprobada',50,45);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (38,'2022-11-28','rechazada',10,28);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (39,'2023-04-13','rechazada',19,4);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (40,'2024-02-18','aprobada',1,40);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (41,'2023-03-22','aprobada',36,39);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (42,'2023-03-27','aprobada',26,38);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (43,'2023-04-11','pendiente',35,3);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (44,'2023-12-13','aprobada',8,4);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (45,'2023-05-15','aprobada',42,2);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (46,'2024-05-20','rechazada',1,20);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (47,'2024-06-18','aprobada',36,8);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (48,'2023-10-19','aprobada',39,15);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (49,'2024-02-02','aprobada',27,21);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (50,'2024-05-29','pendiente',22,50);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (51,'2024-06-07','rechazada',48,44);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (52,'2024-06-12','rechazada',36,16);
INSERT INTO `solicitud_adopcion` (`id_solicitud`,`fecha_solicitud`,`estado`,`id_usuario`,`id_mascota`) VALUES (53,'2024-08-05','aprobada',43,7);

-- Inserción de registros en la tabla 'visita'

INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (1,'2024-11-15',4,1);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (2,'2024-11-14',3,2);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (3,'2024-11-10',8,3);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (4,'2024-11-12',20,4);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (5,'2023-07-17',40,3);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (6,'2020-07-26',45,12);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (7,'2020-02-16',47,17);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (8,'2024-03-26',17,54);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (9,'2022-04-25',37,28);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (10,'2021-07-24',23,19);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (11,'2021-06-02',40,45);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (12,'2022-11-20',30,47);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (13,'2023-11-13',16,13);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (14,'2022-05-10',6,23);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (15,'2022-09-26',7,48);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (16,'2023-10-06',6,14);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (17,'2024-11-01',41,25);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (18,'2023-09-24',53,22);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (19,'2022-12-30',15,10);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (20,'2022-11-14',8,49);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (21,'2024-05-28',31,54);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (22,'2024-09-09',25,33);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (23,'2023-12-11',35,7);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (24,'2024-08-03',14,20);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (25,'2020-10-14',15,44);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (26,'2024-08-22',20,8);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (27,'2023-04-19',6,29);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (28,'2024-04-21',20,18);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (29,'2023-12-22',7,38);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (30,'2023-10-25',17,17);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (31,'2023-03-09',6,41);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (32,'2024-03-25',15,17);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (33,'2020-08-20',43,25);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (34,'2024-05-02',52,50);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (35,'2021-03-07',4,1);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (36,'2024-06-28',10,25);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (37,'2022-08-17',18,52);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (38,'2023-06-08',6,13);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (39,'2024-08-29',7,45);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (40,'2022-09-04',35,9);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (41,'2022-07-15',49,18);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (42,'2023-10-11',34,35);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (43,'2024-03-23',53,15);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (44,'2024-01-24',39,50);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (45,'2024-09-16',32,29);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (46,'2021-01-31',25,6);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (47,'2021-11-09',22,49);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (48,'2021-03-17',52,17);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (49,'2021-11-28',4,1);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (50,'2022-05-09',11,28);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (51,'2024-03-28',38,7);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (52,'2023-12-12',27,30);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (53,'2024-01-26',40,25);
INSERT INTO `visita` (`id_visita`,`fecha_visita`,`id_usuario`,`id_mascota`) VALUES (54,'2022-09-28',48,53);
